### ISSUE TITLE
Need clarification on PID and values on processPID method

### ISSUE THREAD

**Issue by etnaskynet** [maciekelga/Mazda-6-GJ-GL-DPF#1]
Hello,

   in your code you have the PID = 220434, but in processPID you're passing 34 and 1076.
   ********
   DPF_LRD = vlink.processPID(34, 1076, 4, 4, 1, 0); //PID odleglosci od ostatniego wypalania, PID 220434; Equation:((B<16)+(C<8)+D)*( 
   1/640 )_
   *********
   Why?

   If I need to check my PID 22242C, what are the two values to pass with processPID ?

Regards.

**Comment by maciekelga** [comment]
Hi,
PID itself is coded in HEX, but for processPID value need to be in DEC
PID HEX 22 0434 = DEC 34 1076 

For 22 242C You need 34 9260.

**Comment by etnaskynet** [comment]
Hello Maciekelta,

   this should work? It is fine for you?

DPF_KM = myELM327.processPID(34, 9556, 4, 4, 1, 0); //PID 222554; Equation: ((A*256)+B)
  if (myELM327.nb_rx_state == ELM_SUCCESS)
  { 
    D = myELM327.responseByte_0;
    C = myELM327.responseByte_1;
    B = myELM327.responseByte_2;
    A = myELM327.responseByte_3;
    DPF_KM_calc = ((C*256)+D);
}

**Comment by maciekelga** [comment]
DPF distance PID is included.
